version: 0.0
os: linux

files:             
  - source: /
    destination: ~/ccwebapp

hooks:
  AfterInstall:
   - location: ./codedeploy/afterInstall.sh
     timeout: 180
     runas: centos
  ApplicationStart:
   - location: ./codedeploy/applicationStart.sh
     timeout: 180
     runas: centos
  BeforeInstall:
   - location: ./codedeploy/beforeInstall.sh
     timeout: 180
     runas: centos