version: 0.0
os: linux

files:             
  - source: /
    destination: /home/centos/ccwebapp
permissions:
  - object: /home/centos/
    pattern: "confAws.sh"
    owner: ec2-user
    mode: 777
    type:
      - file
hooks:
  AfterInstall:
   - location: ./codedeploy/afterInstall.sh
     timeout: 180
     runas: root
  ApplicationStart:
   - location: ./codedeploy/applicationStart.sh
     timeout: 180
     runas: root
  BeforeInstall:
   - location: ./codedeploy/beforeInstall.sh
     timeout: 180
     runas: root