version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Install packages for CLI
          command : |
            sudo apt-get update
            sudo apt-get install -y python-pip
            sudo pip install awscli
      - run:
          name: Build Deployment Artifcat
          command : |
            mkdir codedeploy-artifact
            zip -r csye6225-webapp-${CIRCLE_BUILD_NUM}.zip webapp codedeploy/*.sh appspec.yml
            pwd
            ls -al
            mv csye6225-webapp-${CIRCLE_BUILD_NUM}.zip codedeploy-artifact/
            ls -al
            pwd
            cd codedeploy-artifact
            pwd
            ls -al
            cd ..
            pwd
            ls -al
      - run:
          name: Copy Artifactto S3
          command: aws s3 sync ./codedeploy-artifact s3://codedeploy.dev.ajaygoel.me